### ISSUE TITLE
Integrate Google Translator

### ISSUE THREAD

**Issue by mslonik** [mslonik/VariousFunctions#12]
1. Find it on the AutoHotkey forum.
2. Integrate within this script, but this time as external file (#include).

**Comment by haniaziet25** [comment]
https://www.autohotkey.com/boards/viewtopic.php?f=6&t=63835&sid=906315d6c0c267a42ca333516fcfa80c&start=160

**Comment by mslonik** [comment]
Solved by haniaziet25 and integrated.
