### ISSUE TITLE
Parenthesis watcher: add tooltip when fired

### ISSUE THREAD

**Issue by mslonik** [mslonik/VariousFunctions#14]
Add option: Tooltip after firing up of Hotstring related to parenthesis watcher. To provide feedback to user about what is going on. Optionally enabled / disabled.

**Comment by haniaziet25** [comment]
Jak użytkownik wywoła funkcję, na końcu powienien sie pojawic tooltip, że skrypt zadzialal

**Comment by haniaziet25** [comment]
widoczny przez 1 s
i gaśnie sam

**Comment by haniaziet25** [comment]
Done!
