### ISSUE TITLE
Capitalization switcher: Caps Lock

### ISSUE THREAD

**Issue by mslonik** [mslonik/VariousFunctions#2]
Change hotkey from Shift + F3 to Caps Lock: https://jacks-autohotkey-blog.com/2020/03/09/auto-capitalize-the-first-letter-of-sentences/

**Comment by haniaziet25** [comment]
Something is wrong with the function

**Comment by haniaziet25** [comment]
I added new Hotkey - Capslock. Now, a user can choose if he wants to use Shift +F3 or Capslock.

**Comment by haniaziet25** [comment]
But I think it is good idea to make separate option in the menu for both shortcuts, because Capslock can be in use already

**Comment by haniaziet25** [comment]
Done!
