### ISSUE TITLE
Show tick icons for enabled functions

### ISSUE THREAD

**Issue by mslonik** [mslonik/VariousFunctions#5]
In the left column of Tray menu show tick mark: ☑ if function is enabled.

**Comment by haniaziet25** [comment]
Somthing is wrong with MenuItemName - it works only in Always on Top, but for the rest there is an error - Nonexistent menu item
Example:
![image](https://user-images.githubusercontent.com/95625092/157440789-3967d94f-d9b0-41a3-b507-cd15d5e45596.png)

**Comment by mslonik** [comment]
Solved by Kasandra01. Dedicated GUI with ticks.
